import React,{useState} from 'react';
import Head from 'next/head'
import Container from '../components/Container'
import Card from '../components/Card'
import Modal from '../components/Modal'
import Titlecard from '../components/TitleCard'
import Github from '../components/Github'
import Imagecard from '../components/ImageCard';

export default function Home() {

  return (
    <Container>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container grid mx-auto my-5 px-4 h-full relative grid-cols-12 gap-5 auto-rows-300 md:auto-rows-400 xl:auto-rows-500">

        <Card 
          classes={"flex justify-end items-center xl:items-end xl:flex-row flex-col col-start-1 col-end-13 bg-violet-100"}>

          <h1 className="2xl:text-6xl lg:text-5xl md:text-3xl text-2xl text-center font-bold pt-5 lg:pt-10 self-center">
            I’m <span className="text-violet-400">Eduardo</span>. I like to develop websites
          </h1>

          <Imagecard classes='h-60 w-60 md:h-72 md:w-72 xl:h-96 xl:w-96 relative -bottom-1' imgSrc='/img/edumoji.png' />

        </Card>

        <Card isModal color='blue' classes={"flex justify-end items-end bg-blue-100 col-start-1 col-end-13 lg:col-end-6"}>

          <Imagecard classes='h-80 w-80 md:h-100 md:w-100 relative -bottom-1' imgSrc='/img/eduabout.png' />

          <Titlecard
            classes={'text-blue-400 -bottom-20 sm:-bottom-16 xl:-bottom-10 2xl:-bottom-0 -left-36 sm:-left-24 lg:-left-32 xl:-left-32 2xl:-left-20 transform scale-40 sm:scale-60 lg:scale-50 xl:scale-75 2xl:scale-100'}  
            title={'About'}
          />

        </Card>             

        <Card isModal color='yellow' classes={"flex justify-end items-end col-start-1 col-end-13 lg:col-start-6 bg-yellow-100"}>

        <Imagecard classes='h-72 w-72 md:h-96 md:w-96 relative -bottom-8' imgSrc='/img/eduprojects.png' />

          <Titlecard 
            classes={'text-yellow-400 -top-20 sm:-top-16 xl:-top-12 2xl:-top-8 -left-48 sm:-left-32 xl:-left-20 2xl:-left-2 transform scale-40 sm:scale-60 lg:scale-6 xl:scale-75 2xl:scale-100'}
            title={'Projects'}
            spaceLetter={true}
          />

        </Card>

        <Card isModal color='green' classes={'col-start-1 col-end-13 bg-green-100 flex justify-center items-center'}>

          <Imagecard classes='h-102 w-102 relative -bottom-16' imgSrc='/img/eduskills.png' />

          <Titlecard 
            classes={'text-green-400 top-22 -left-36 sm:-left-36 md:-left-32 xl:top-22 xl:-left-20 transform rotate-90 scale-60 md:scale-75 xl:scale-100'}
            title={'Skills'}
          />

        </Card>
      </div>

      <div className='container grid px-4 mb-5 h-full relative grid-cols-12 gap-5 auto-rows-100 sm:auto-rows-150 md:auto-rows-200'>
        <a href="https://github.com/edudotdev" target='_blank' rel="noreferrer" className='col-start-1 col-end-13 sm:col-start-1 sm:col-end-5 grid'>
        <Card
          classes={'flex justify-center items-center bg-gray-100'} >

          <Github /> 

          <Imagecard classes='h-40 w-40 transform scale-40 sm:scale-60 md:scale-75 lg:scale-100 relative' imgSrc='/img/github.png' />

        </Card>
        </a>

        <a href="https://twitter.com/edurl_dev" target='_blank' rel="noreferrer" className='col-start-1 col-end-13 sm:col-start-5 sm:col-end-9 grid'>
        <Card
          classes={'flex justify-center items-center bg-blue-400'} >

        <Imagecard classes='h-28 w-32 transform scale-40 sm:scale-60 md:scale-75 lg:scale-100 relative' imgSrc='/img/tt.webp' />

        </Card>
        </a>

        <a href="https://www.linkedin.com/in/eduardo-guadalupe-robles-ley-9b0807205/" target='_blank' rel="noreferrer" className='col-start-1 col-end-13 sm:col-start-9 sm:col-end-13 grid'>
        <Card
          classes={'flex justify-center items-center bg-gray-100'} >
          
          <Imagecard classes='h-32 w-64 block sm:hidden lg:block transform scale-50 md:scale-60 lg:scale-75 xl:scale-100 relative' imgSrc='/img/linkedin.png' />

          <Imagecard classes='h-20 w-20 md:h-24 md:w-24 hidden sm:block lg:hidden transform relative' imgSrc='/img/in.png' />

        </Card>
        </a>

      </div>
    </Container>
  )
}
