import Head from 'next/head'
import Container from '../components/Container'
import Skill from '../components/skill'
import Card from '../components/Card'
import BtnModal from '../components/BtnModal'
import Modal from '../components/Modal'
import Image from 'next/Image'

export default function Home() {
  return (
    <div className="wrapper_index ">
    

    <Container className="indexx">
      <Head>
        <title>Portfolio - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="wrapper container grid mx-auto h-full relative grid-cols-12 gap-5 auto-rows-500 mt-20">

        <Card 
          classes={"flex justify-end items-end col-start-1 col-end-13 bg-purple-100"}>

          <h1 className="2xl:text-6xl lg:text-5xl md:text-3xl text-2xl text-center font-bold py-16 self-center">
            I’m <span className="text-purple-500">Eduardo</span>. I like to develop websites
          </h1>
          <Image 
            src="/img/edumoji.png"
            height={421}
            width={421}
          />
          <Modal>
            1
          </Modal>
        </Card>

        <Card 
          classes={"flex justify-center items-end bg-blue-300 col-start-1 col-end-6"}>
          <Modal>
            2
          </Modal>
        </Card>
        
        <Card 
          classes={"flex justify-center items-end col-start-6 col-end-13 bg-red-300"}>
          <Modal>
            3
          </Modal>
        </Card>

          {/* <Image 
            src="/img/RadialCircle.svg"
            height={500}
            width={500}
          /> */}
           
          {/* <div className="avatar">
            <Image 
              src="/img/edumoji.png"
              height={421}
              width={421}
            />
          </div> */}
          {/* <Skill 
            skill={'HTML'}
            bottom={'18%'}
            left={'calc(6vw + 12%)'}
          />
          <Skill 
            skill={'CSS'}
            bottom={'22%'}
            right={'calc(10vw + 16%)'}
          />
          <Skill 
            skill={'JS'}
            top={'40%'}
            left={'calc(16vw + 6% + 30px)'}
          />
          <Skill 
            skill={'REACT'}
            top={'25%'}
            right={'calc(16vw + 10% + 25px)'}
          /> */}
      </div>
    </Container>
    </div>
  )
}
